import type {
	AiArchetype,
	CombatAction,
	MercenaryState,
} from "@relic-hunter/shared";

import type { Game } from "@/core/game/Game";
import {
	BattleOverlay,
	type BattleResult,
	type LocalHumanRole,
} from "@/ui/overlay/BattleOverlay";

/**
 * Result returned to the caller after the BattleOverlay has completely
 * finished its lifecycle.
 *
 * BattleHost deliberately does not know what a "teleport" or "monster died"
 * means on the map. It only returns the result produced by the battle UI.
 */
export type BattleHostResult = BattleResult;

/**
 * Optional tutorial configuration.
 *
 * The host owns the integration seam, but tutorial prose / failure handling
 * remains outside BattleHost.
 */
export interface BattleTutorialOptions {
	/**
	 * Restrict the action buttons shown by BattleOverlay.
	 *
	 * Example:
	 * ["defend"]
	 */
	availableActions?: CombatAction[];

	/**
	 * Optional gate used to reject an action before card selection.
	 *
	 * The caller owns the feedback/event generated by a rejected action.
	 */
	actionGate?: (action: CombatAction) => boolean;

	/**
	 * Fires after BattleOverlay has built and laid out.
	 *
	 * Useful for tutorial pointer positioning.
	 */
	onReady?: () => void;
}

/**
 * Complete description of one client-side battle.
 *
 * BattleHost owns construction of BattleOverlay from this request.
 * MapScene / MapController supply state and map-specific callbacks.
 */
export interface BattleRequest {
	attackerState: MercenaryState;
	defenderState: MercenaryState;

	attackerColor: number;
	attackerLabel: string;

	defenderColor: number;
	defenderLabel: string;

	attackerArchetype?: AiArchetype;
	defenderArchetype?: AiArchetype;

	localHumanRole?: LocalHumanRole;

	attackerMapCoord: { x: number; y: number };
	defenderMapCoord: { x: number; y: number };

	/**
	 * True when the attack was initiated as a ranged attack.
	 */
	isRangedInitiated?: boolean;

	/**
	 * Whether either side represents a monster.
	 */
	isAttackerMonster?: boolean;
	isDefenderMonster?: boolean;

	/**
	 * Maximum number of combat rounds.
	 */
	maxRounds?: number;

	/**
	 * Optional tutorial-specific restrictions.
	 */
	tutorial?: BattleTutorialOptions;

	/**
	 * Called after BattleOverlay has completely finished.
	 *
	 * This is where MapScene / MapController can translate the result into
	 * actual map consequences.
	 */
	onComplete?: (result: BattleHostResult) => void;
}

/**
 * Client-side combat integration seam.
 *
 * Architectural ownership:
 *
 *     MapController / TutorialPort
 *              |
 *              v
 *         BattleHost
 *              |
 *              v
 *        BattleOverlay
 *              |
 *              v
 *        BattleResult
 *
 * BattleHost is intentionally small.
 */
export class BattleHost {
	constructor(private readonly game: Game) {}

	/**
	 * Start a battle and resolve when the complete battle flow has finished.
	 */
	async run(request: BattleRequest): Promise<BattleHostResult> {
		return new Promise<BattleHostResult>((resolve) => {
			let completed = false;

			const complete = (result: BattleHostResult): void => {
				if (completed) return;

				completed = true;

				request.onComplete?.(result);
				resolve(result);
			};

			const overlay = new BattleOverlay(
				this.game,

				request.attackerState,
				request.defenderState,

				complete,

				request.attackerColor,
				request.attackerLabel,

				request.defenderColor,
				request.defenderLabel,

				request.attackerArchetype ?? "balanced",
				request.defenderArchetype ?? "balanced",

				request.localHumanRole ?? "attacker",

				request.attackerMapCoord,
				request.defenderMapCoord,

				request.isRangedInitiated ?? false,

				request.tutorial?.availableActions,

				request.isAttackerMonster ?? false,
				request.isDefenderMonster ?? false,

				request.maxRounds ?? 3,
			);

			/**
			 * Tutorial / guided combat may reject an action before the
			 * BattleOverlay enters card selection.
			 */
			if (request.tutorial?.actionGate) {
				overlay.setActionGate(request.tutorial.actionGate);
			}

			/**
			 * Tutorial pointers sometimes need to wait until the overlay has
			 * actually laid itself out before asking for button positions.
			 */
			if (request.tutorial?.onReady) {
				overlay.setOnReady(request.tutorial.onReady);
			}

			/**
			 * OverlayManager is the single global overlay lifecycle owner.
			 */
			void this.game.overlays.show(overlay);
		});
	}

	/**
	 * Convenience wrapper for the normal local-player battle path.
	 *
	 * This keeps common production calls short while still routing through
	 * the exact same host.
	 */
	async runLocalBattle(
		attackerState: MercenaryState,
		defenderState: MercenaryState,
		options: Omit<
			BattleRequest,
			"attackerState" | "defenderState" | "localHumanRole"
		>,
	): Promise<BattleHostResult> {
		return this.run({
			...options,
			attackerState,
			defenderState,
			localHumanRole: "attacker",
		});
	}
}
